# Generated by Django 3.2.7 on 2021-09-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0003_delete_shinydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShinyData',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Number')),
                ('alph_seri', models.CharField(max_length=20, null=True, verbose_name='Alph_seri')),
                ('contributor', models.CharField(max_length=50, null=True, verbose_name='Contributor')),
                ('survNo', models.IntegerField(null=True, verbose_name='SurvNo')),
                ('date', models.CharField(max_length=15, null=True, verbose_name='Date')),
                ('time', models.TimeField(max_length=10, null=True, verbose_name='Time')),
                ('season', models.CharField(max_length=10, null=True, verbose_name='Season')),
                ('loc', models.CharField(max_length=30, null=True, verbose_name='Location')),
                ('svf', models.CharField(max_length=30, null=True, verbose_name='SVF')),
                ('city_country', models.CharField(max_length=50, null=True, verbose_name='City/Country')),
                ('climate', models.CharField(max_length=30, null=True, verbose_name='Climate')),
                ('gender', models.CharField(max_length=1, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(null=True, verbose_name='Exact Age')),
                ('agegrp', models.CharField(max_length=30, null=True, verbose_name='Age Group')),
                ('height', models.FloatField(null=True, verbose_name='Height')),
                ('weight', models.FloatField(null=True, verbose_name='Weight')),
                ('thermal_sensation_vote_7', models.IntegerField(null=True, verbose_name='Thermal Sensation Vote (7-pt)')),
                ('thermal_sensation_vote_9', models.IntegerField(null=True, verbose_name='Thermal Sensation Vote (9-pt)')),
                ('thermal_comfort_vote', models.IntegerField(null=True, verbose_name='Thermal Comfort Vote')),
                ('thermal_preference_vote_7', models.IntegerField(null=True, verbose_name='Thermal Preference Vote (7-pt)')),
                ('thermal_preference', models.IntegerField(null=True, verbose_name='Thermal Preference (3-pt scale)')),
                ('thermal_acceptance', models.IntegerField(null=True, verbose_name='Thermal Acceptance')),
                ('wind_sensation_vote', models.IntegerField(max_length=30, null=True, verbose_name='Wind Sensation Vote')),
                ('solar_sensation_vote', models.IntegerField(max_length=30, null=True, verbose_name='Solar Sensation Vote')),
                ('humidity_sensation_vote', models.IntegerField(max_length=30, null=True, verbose_name='Humidity Sensation Vote')),
                ('metabolic_rate', models.FloatField(null=True, verbose_name='Metabolic Rate')),
                ('clothing_index', models.FloatField(null=True, verbose_name='Clothing Index')),
                ('thermal_history', models.CharField(max_length=30, null=True, verbose_name='Thermal History')),
                ('air_temp', models.FloatField(null=True, verbose_name='Air Temperature')),
                ('relative_humidity', models.FloatField(null=True, verbose_name='Relative Humidity')),
                ('wind_speed', models.FloatField(null=True, verbose_name='Wind SpeedS')),
                ('global_temp', models.FloatField(null=True, verbose_name='Global Temperature')),
                ('mean_radiant_temp', models.FloatField(null=True, verbose_name='Mean Radiant Temperature')),
                ('radiation', models.FloatField(null=True, verbose_name='Radiation')),
                ('pet', models.FloatField(null=True, verbose_name='PET')),
                ('utci', models.FloatField(null=True, verbose_name='UTCI')),
                ('vp', models.FloatField(null=True, verbose_name='VP')),
            ],
        ),
    ]
