# Generated by Django 3.2.7 on 2021-09-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0004_shinydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShinyDataSet',
        ),
    ]
