# Generated by Django 3.2.7 on 2021-09-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0005_delete_shinydataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shinydata',
            name='humidity_sensation_vote',
            field=models.IntegerField(null=True, verbose_name='Humidity Sensation Vote'),
        ),
        migrations.AlterField(
            model_name='shinydata',
            name='solar_sensation_vote',
            field=models.IntegerField(null=True, verbose_name='Solar Sensation Vote'),
        ),
        migrations.AlterField(
            model_name='shinydata',
            name='wind_sensation_vote',
            field=models.IntegerField(null=True, verbose_name='Wind Sensation Vote'),
        ),
    ]
