# Generated by Django 3.2.7 on 2021-09-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0002_shinydataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShinyData',
        ),
    ]
