from django.db import models


class ShinyData(models.Model):
    no = models.IntegerField(primary_key=True, verbose_name="Number")
    alph_seri = models.CharField(verbose_name="Alph_seri", max_length=20, null=True)
    contributor = models.CharField(verbose_name="Contributor", max_length=50, null=True)
    survNo = models.IntegerField(verbose_name="SurvNo", null=True)
    date = models.CharField(verbose_name="Date", max_length=15, null=True)
    time = models.TimeField(verbose_name="Time", max_length=10, null=True)
    season = models.CharField(verbose_name="Season", max_length=10, null=True)
    loc = models.CharField(verbose_name="Location", max_length=30, null=True)
    svf = models.CharField(verbose_name="SVF", max_length=30, null=True)
    city_country = models.CharField(verbose_name="City/Country", max_length=50, null=True)
    climate = models.CharField(verbose_name="Climate", max_length=30, null=True)
    gender = models.CharField(verbose_name="Gender", max_length=1, null=True)
    age = models.IntegerField(verbose_name="Exact Age", null=True)
    agegrp = models.CharField(verbose_name="Age Group", max_length=30, null=True)
    height = models.FloatField(verbose_name="Height", null=True)
    weight = models.FloatField(verbose_name="Weight", null=True)
    thermal_sensation_vote_7 = models.IntegerField(verbose_name="Thermal Sensation Vote (7-pt)", null=True)
    thermal_sensation_vote_9 = models.IntegerField(verbose_name="Thermal Sensation Vote (9-pt)", null=True)
    thermal_comfort_vote = models.IntegerField(verbose_name="Thermal Comfort Vote", null=True)
    thermal_preference_vote_7 = models.IntegerField(verbose_name="Thermal Preference Vote (7-pt)", null=True)
    thermal_preference = models.IntegerField(verbose_name="Thermal Preference (3-pt scale)", null=True)
    thermal_acceptance = models.IntegerField(verbose_name="Thermal Acceptance", null=True)
    wind_sensation_vote = models.IntegerField(verbose_name="Wind Sensation Vote", null=True)
    solar_sensation_vote = models.IntegerField(verbose_name="Solar Sensation Vote", null=True)
    humidity_sensation_vote = models.IntegerField(verbose_name="Humidity Sensation Vote", null=True)
    metabolic_rate = models.FloatField(verbose_name="Metabolic Rate", null=True)
    clothing_index = models.FloatField(verbose_name="Clothing Index", null=True)
    thermal_history = models.CharField(verbose_name="Thermal History", max_length=30, null=True)
    air_temp = models.FloatField(verbose_name="Air Temperature", null=True)
    relative_humidity = models.FloatField(verbose_name="Relative Humidity", null=True)
    wind_speed = models.FloatField(verbose_name="Wind SpeedS", null=True)
    global_temp = models.FloatField(verbose_name="Global Temperature", null=True)
    mean_radiant_temp = models.FloatField(verbose_name="Mean Radiant Temperature", null=True)
    radiation = models.FloatField(verbose_name="Radiation", null=True)
    pet = models.FloatField(verbose_name="PET", null=True)
    utci = models.FloatField(verbose_name="UTCI", null=True)
    vp = models.FloatField(verbose_name="VP", null=True)
